(() => {
  'use strict';
  const MIN_BUDGET_TOMAN=500_000_000, PRICE_WINDOW_MILLION=100, MARKET_NEAR_PERCENT=3;
  const MARKET_FEED_URL='https://raw.githubusercontent.com/Morijooob/dastyar-khodro/main/data/market-prices.json';
  const safeChecked=name=>document.querySelector(`input[name="${name}"]:checked`);
  const fa=n=>Number(n||0).toLocaleString('fa-IR');
  const faText=v=>String(v??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[Number(d)]);
  const normalizeDigits=v=>String(v??'').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[٬,]/g,'').replace(/[٫]/g,'.');
  const parseBudgetToman=v=>{const n=Number(normalizeDigits(v).trim());return Number.isFinite(n)?n:0};
  const cityNames={all:'همه شهرها',tehran:'تهران',mashhad:'مشهد',isfahan:'اصفهان',shiraz:'شیراز',tabriz:'تبریز',karaj:'کرج',ahvaz:'اهواز',qom:'قم',kermanshah:'کرمانشاه',rasht:'رشت',urmia:'ارومیه',yazd:'یزد',kerman:'کرمان',arak:'اراک','bandar-abbas':'بندرعباس'};
  async function refreshMarketPrices(){try{const r=await fetch(`${MARKET_FEED_URL}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const j=await r.json();if(Array.isArray(j.prices)&&j.prices.length){const local=Array.isArray(window.marketPrices)?window.marketPrices:[];window.marketPrices=[...local,...j.prices]}}catch(e){console.log('Remote market feed skipped:',e)}}
  const marketFeedPromise=refreshMarketPrices();
  function getMarketInfo(car){const rows=Array.isArray(window.marketPrices)?window.marketPrices:[];const m=rows.filter(x=>x.carId===car.id&&Number.isFinite(Number(x.price))&&x.date);if(!m.length)return{price:Number(car.price),date:null,sources:[]};const d=m.map(x=>x.date).sort().reverse()[0],latest=m.filter(x=>x.date===d);return{price:Math.round(latest.reduce((s,x)=>s+Number(x.price),0)/latest.length),date:d,sources:[...new Set(latest.map(x=>x.source).filter(Boolean))]}}
  function marketStatus(c){const i=getMarketInfo(c);if(!c.bestListing||!Number.isFinite(Number(c.bestListing.price))||!Number.isFinite(Number(i.price))||i.price<=0)return'<div class="price-change flat">ℹ️ آگهی زنده و تأییدشده‌ای برای مقایسه این خودرو در بانک فعلی نداریم.</div>';const pct=(Number(c.bestListing.price)-i.price)/i.price*100,r=Math.abs(pct)<.1?0:Math.round(Math.abs(pct)*10)/10;if(Math.abs(pct)<=MARKET_NEAR_PERCENT)return`<div class="price-change flat">🟡 نزدیک به متوسط قیمت بازار · ${fa(i.price)} میلیون تومان <small>(${faText(i.date)} · مرجع بازار)</small></div>`;return pct<0?`<div class="price-change down">🟢 پایین‌تر از قیمت بازار · ${fa(r)}٪ کمتر از متوسط بازار</div>`:`<div class="price-change up">🔴 بالاتر از قیمت بازار · ${fa(r)}٪ بیشتر از متوسط بازار</div>`}
  function divarUrl(city,carName){const slug=city==='all'?'tehran':city;return`https://divar.ir/s/${encodeURIComponent(slug)}/car?query=${encodeURIComponent(carName||'خودرو')}`}
  function getListings(car,city='all'){if(typeof window.getVerifiedListings==='function')return window.getVerifiedListings(car.id,city);return[]}
  function calculateValueScore(car,p,marketPrice,bestListing){
    const budget=Number(p.budget)||0,market=Number(marketPrice)||Number(car.price)||0,listing=bestListing&&Number.isFinite(Number(bestListing.price))?Number(bestListing.price):null,price=listing??market;
    let score=0;const reasons=[];const details=[];
    if(market>0&&price>0){const discount=((market-price)/market)*100;const points=Math.max(8,Math.min(30,20+discount*1.5));score+=points;details.push({key:'market',label:'قیمت نسبت به بازار',points:Math.round(points),max:30});if(discount>=5)reasons.push(`قیمت ${Math.round(discount)}٪ پایین‌تر از متوسط بازار است.`);else if(discount<=-5)reasons.push(`قیمت حدود ${Math.round(Math.abs(discount))}٪ بالاتر از متوسط بازار است.`);else reasons.push('قیمت به متوسط بازار نزدیک است.')}else details.push({key:'market',label:'قیمت نسبت به بازار',points:0,max:30});
    if(budget>0&&price>0){const gap=Math.abs(price-budget)/budget*100;const points=Math.max(5,20-Math.min(15,gap*.8));score+=points;details.push({key:'budget',label:'تناسب با بودجه',points:Math.round(points),max:20});if(price<=budget)reasons.push('داخل بودجه شما قرار می‌گیرد.');else reasons.push(`حدود ${fa(Math.round(price-budget))} میلیون تومان بالاتر از بودجه است.`)}else details.push({key:'budget',label:'تناسب با بودجه',points:0,max:20});
    let suitability=0;if(p.gearbox==='any'||car.gearbox===p.gearbox)suitability+=5;if(Array.isArray(car.uses)&&car.uses.includes(p.use))suitability+=5;if(p.passengers>=5&&(car.passengers||5)>=5)suitability+=3;if(p.passengers<=2&&Array.isArray(car.uses)&&car.uses.includes('city'))suitability+=2;if(suitability===0)suitability=7;else if(suitability<7)suitability=7;score+=suitability;details.push({key:'suitability',label:'تناسب با نیاز شما',points:suitability,max:15});if(suitability>=10)reasons.push('با نیاز و نوع استفاده شما تناسب خوبی دارد.');
    const maintenance=Number.isFinite(Number(car.maintenance))?Math.max(0,Math.min(10,Number(car.maintenance))):6;score+=maintenance;details.push({key:'maintenance',label:'هزینه نگهداری',points:Math.round(maintenance),max:10});
    const economy=Number.isFinite(Number(car.economy))?Math.max(0,Math.min(8,Number(car.economy)*.8)):5;score+=economy;details.push({key:'economy',label:'مصرف سوخت',points:Math.round(economy),max:8});
    const resale=Number.isFinite(Number(car.resale))?Math.max(0,Math.min(7,Number(car.resale)*.7)):5;score+=resale;details.push({key:'resale',label:'بازار فروش مجدد',points:Math.round(resale),max:7});
    const live=bestListing?5:0;score+=live;details.push({key:'live',label:'آگهی واقعی فعلی',points:live,max:5});
    let ys=0;if(p.year==='new')ys=Math.min(5,Math.max(0,(Number(car.year)-1398)*.85));else if(p.year==='old')ys=Math.min(5,Math.max(0,(1403-Number(car.year))*.85));else if(p.year==='balanced')ys=4;score+=ys;details.push({key:'year',label:'مدل و سال خودرو',points:Math.round(ys),max:5});
    const finalScore=Math.max(0,Math.min(100,Math.round(score)));return{score:finalScore,reasons:reasons.slice(0,5),details};
  }
  function valueLabel(s){if(s>=85)return{label:'عالی',icon:'🟢'};if(s>=70)return{label:'خوب',icon:'🟢'};if(s>=55)return{label:'متوسط',icon:'🟡'};if(s>=40)return{label:'ضعیف',icon:'🟠'};return{label:'نامناسب',icon:'🔴'}}
  function opportunityScore(car,p,bestListing){if(!bestListing)return null;const market=getMarketInfo(car).price,lp=Number(bestListing.price);let s=40;if(market>0)s+=Math.max(-15,Math.min(35,(market-lp)/market*100*1.5));if(Number(p.budget)>0)s+=lp<=Number(p.budget)?20:Math.max(-20,20-(lp-Number(p.budget))/Number(p.budget)*100*2);return Math.max(0,Math.min(100,Math.round(s)))}
  function scoreCar(car,p){const market=getMarketInfo(car),listings=getListings(car,p.city),bestListing=listings.filter(x=>Number.isFinite(Number(x.price))&&Math.abs(Number(x.price)-p.budget)<=PRICE_WINDOW_MILLION).sort((a,b)=>Math.abs(Number(a.price)-p.budget)-Math.abs(Number(b.price)-p.budget))[0]||null,value=calculateValueScore(car,p,market.price,bestListing);return{...car,price:market.price,difference:market.price-p.budget,absoluteDifference:Math.abs(market.price-p.budget),marketDate:market.date,marketSources:market.sources,match:value.score,valueScore:value.score,valueLabel:valueLabel(value.score),opportunityScore:opportunityScore(car,p,bestListing),reasons:value.reasons,scoreDetails:value.details,bestListing,listingCity:bestListing?.city||cityNames[p.city]||'همه شهرها',divarUrl:bestListing?.url&&bestListing.url!=='#'?bestListing.url:divarUrl(p.city,car.name||car.title)}}
  function removeResults(){document.getElementById('results')?.remove();document.getElementById('app-error')?.remove()}
  function marketplaceLinks(c){const gap=c.difference===0?'هم‌قیمت':`${c.difference>0?'+':''}${Math.round(c.difference).toLocaleString('fa-IR')} میلیون`;if(c.bestListing){const source=c.bestListing.source||'منبع';return`<div class="listing-summary"><div><strong>🟢 آگهی تأییدشده</strong><span>${c.bestListing.city} · ${source} · ${fa(c.bestListing.price)} میلیون تومان</span></div><div class="marketplace-actions"><a class="listing-link" href="${c.bestListing.url}" target="_blank" rel="noopener noreferrer">مشاهده آگهی در ${source}</a></div><small>آخرین مشاهده: ${c.bestListing.observedAt?faText(c.bestListing.observedAt):'نامشخص'} · اختلاف با بودجه: ${gap}</small></div>`}return`<div class="listing-summary"><div><strong>🛒 جستجوی بازار</strong><span>${cityNames[c.listingCity]||c.listingCity} · هنوز آگهی زنده تأییدشده نداریم</span></div><div class="marketplace-actions"><a class="listing-link" href="${c.divarUrl}" target="_blank" rel="noopener noreferrer">دیوار</a></div><small>این مسیر جستجوی بازار است، نه آگهی مشخص. اطلاعات ساختگی وارد سیستم نمی‌کنیم.</small></div>`}
  function scoreDetailsHtml(c){const rows=(c.scoreDetails||[]).map(d=>`<div class="score-detail-row"><span>${d.label}</span><strong>${faText(d.points)} از ${faText(d.max)}</strong></div>`).join('');return`<div class="score-details"><div class="score-details-title">📊 جزئیات امتیاز ارزش خرید</div><div class="score-detail-list">${rows}</div><div class="score-detail-total"><span>🏆 امتیاز نهایی</span><strong>${faText(c.valueScore)} از ۱۰۰</strong></div></div>`}
  function render(results,p){removeResults();const section=document.createElement('section');section.id='results';section.className='results';section.innerHTML=`<div class="results-head"><div><span class="eyebrow">تحلیل دستیار خودرو</span><h2>🚗 پیشنهادهای نزدیک به بودجه تو</h2></div><span class="experimental">نسخه ${window.APP_VERSION||'1.3.0'}</span></div>`+results.map((c,i)=>`<article class="result-card ${i===0?'top-pick':''}"><div class="result-top"><div><span class="rank">${i===0?'🏆 پیشنهاد اول':`گزینه ${i+1}`}</span><h3>${c.name||c.title||'خودرو'}</h3></div><div class="score"><strong>${c.valueScore}%</strong><small>ارزش خرید</small></div></div><div class="price">💰 ${fa(c.price)} میلیون تومان</div><div class="price-meta">متوسط قیمت بازار · بروزرسانی: ${c.marketDate?faText(c.marketDate):'نامشخص'} · بودجه شما: ${fa(p.budget)} میلیون تومان · شهر: ${cityNames[p.city]}</div>${marketStatus(c)}<div class="value-badge">${c.valueLabel.icon} ارزش خرید: <strong>${c.valueLabel.label}</strong></div>${scoreDetailsHtml(c)}<div class="reason-title">چرا این گزینه؟</div><ul>${c.reasons.map(x=>`<li>${x}</li>`).join('')}</ul>${marketplaceLinks(c)}${c.opportunityScore!==null?`<div class="opportunity">🎯 فرصت خرید فعلی: <strong>${c.opportunityScore}٪</strong></div>`:'<div class="opportunity muted">ℹ️ فعلاً آگهی تأییدشده‌ای برای فرصت خرید نداریم.</div>'}${i===0?'<span class="best-badge">⭐ بهترین ارزش خرید در این نتیجه</span>':''}</article>`).join('')+`<div class="data-note">نسخه برنامه: ${window.APP_VERSION||'1.3.0'} · امتیاز ارزش خرید مستقل از وجود آگهی زنده محاسبه می‌شود.</div>`;document.querySelector('main').appendChild(section);section.scrollIntoView({behavior:'smooth',block:'start'})}
  function readParams(){const budget=parseBudgetToman(document.getElementById('budget')?.value);return{budget:budget/1_000_000,city:document.getElementById('city')?.value||'all',gearbox:safeChecked('gearbox')?.value||'any',use:safeChecked('use')?.value||'city',passengers:Number(document.getElementById('passengers')?.value||4),year:safeChecked('year')?.value||'balanced',priority:safeChecked('priority')?.value||'value'}}
  async function run(){const p=readParams();if(p.budget*1_000_000<MIN_BUDGET_TOMAN){alert('لطفاً بودجه را وارد کنید.');return}await marketFeedPromise;const cars=Array.isArray(window.cars)?window.cars:[];const results=cars.map(c=>scoreCar(c,p)).sort((a,b)=>b.valueScore-a.valueScore).slice(0,8);render(results,p)}
  function init(){const form=document.querySelector('form');if(form&&!form.dataset.dastyarBound){form.dataset.dastyarBound='1';form.addEventListener('submit',e=>{e.preventDefault();run().catch(err=>{console.error(err);alert('خطا در تحلیل اطلاعات خودرو.')}})}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();