function getPriceHistory(carId) {
  if (!Array.isArray(marketPrices)) return [];
  return marketPrices.filter(p => p.carId === carId && Number.isFinite(Number(p.price)) && p.date).sort((a,b) => String(b.date).localeCompare(String(a.date)));
}
function getLatestMarketPrice(carId) {
  const history=getPriceHistory(carId); if(!history.length)return null;
  const latestDate=history[0].date, sameDay=history.filter(p=>p.date===latestDate);
  const average=sameDay.reduce((s,p)=>s+Number(p.price),0)/sameDay.length;
  return {price:Math.round(average),date:latestDate,source:sameDay.length>1?'میانگین چند منبع':sameDay[0].source,sourceCount:sameDay.length};
}
function getPreviousMarketPrice(carId) {
  const history=getPriceHistory(carId); if(!history.length)return null;
  const previousDate=history.find(p=>p.date!==history[0].date)?.date; if(!previousDate)return null;
  const sameDay=history.filter(p=>p.date===previousDate), average=sameDay.reduce((s,p)=>s+Number(p.price),0)/sameDay.length;
  return {price:Math.round(average),date:previousDate,source:sameDay.length>1?'میانگین چند منبع':sameDay[0].source,sourceCount:sameDay.length};
}
function getPriceChange(carId){const latest=getLatestMarketPrice(carId),previous=getPreviousMarketPrice(carId);if(!latest||!previous||!previous.price)return null;const amount=latest.price-previous.price,percent=amount/previous.price*100;return{amount,percent,direction:amount>0?'up':amount<0?'down':'flat'};}
function getValueForMoney(car,budget){const budgetFit=budget>0?Math.max(0,Math.min(100,100-Math.abs(car.price-budget)/budget*100)):0;const quality=((car.maintenance||5)+(car.economy||5)+(car.resale||5)+(10-(car.risk||5)))*2.5;const pricePressure=car.price<=budget?100:Math.max(0,100-(car.price-budget)/budget*100);const trendPenalty=car.priceChange&&car.priceChange.percent>10?Math.min(12,car.priceChange.percent-10):0;const score=budgetFit*.35+quality*.35+pricePressure*.30-trendPenalty;return{score:Math.max(0,Math.min(100,score)),value:score>=78?'بالا':score>=62?'متوسط':'پایین'};}
function getListingsForCar(carId){return(Array.isArray(listings)?listings:[]).filter(x=>x.carId===carId&&Number.isFinite(Number(x.price)));}
function getListingValue(listing,referencePrice){const diff=Number(listing.price)-Number(referencePrice);const percent=referencePrice?diff/referencePrice*100:0;return{difference:diff,percent};}
function getListingVerdict(listing,referencePrice){const v=getListingValue(listing,referencePrice);if(v.percent<=-7)return{label:'پایین‌تر از مرجع',tone:'good'};if(v.percent>=7)return{label:'بالاتر از مرجع',tone:'bad'};return{label:'نزدیک به مرجع',tone:'neutral'};}
function getBestListing(car){const items=getListingsForCar(car.id).map(l=>({...l,...getListingValue(l,car.price),verdict:getListingVerdict(l,car.price)})).sort((a,b)=>a.difference-b.difference);return items[0]||null;}
const cars=(Array.isArray(carData)?carData:[]).map(car=>{const market=getLatestMarketPrice(car.id),change=getPriceChange(car.id);return{...car,price:market?market.price:car.price,priceDate:market?market.date:car.priceDate,priceSource:market?market.source:car.priceSource,priceIsMarket:Boolean(market),priceChange:change};});
const form=document.getElementById('car-form');
function scoreCar(car,p){let s=0;const reasons=[],gap=Math.abs(car.price-p.budget)/Math.max(p.budget,1);s+=Math.max(0,30-gap*30);if(car.price<=p.budget){s+=15;reasons.push('داخل بودجه شماست.');}else{s-=Math.min(12,8+gap*10);reasons.push('بالاتر از بودجه شماست؛ گزینه نزدیک‌تری برای مقایسه است.');}if(p.gearbox==='any'||car.gearbox===p.gearbox){s+=20;reasons.push(p.gearbox==='auto'?'گیربکس اتومات مطابق انتخاب شماست.':p.gearbox==='manual'?'گیربکس دنده‌ای مطابق انتخاب شماست.':'گیربکس با نیاز شما سازگار است.');}if(car.uses.includes(p.use)){s+=15;reasons.push(p.use==='city'?'برای استفاده شهری مناسب است.':p.use==='family'?'برای استفاده خانوادگی مناسب است.':'برای سفر مناسب است.');}if((p.priority==='cheap'&&car.maintenance>=7)||(p.priority==='fuel'&&car.economy>=7)||(p.priority==='resale'&&car.resale>=8)){s+=15;reasons.push(p.priority==='cheap'?'هزینه نگهداری امتیاز خوبی دارد.':p.priority==='fuel'?'مصرف اقتصادی‌تری دارد.':'بازار فروش بهتری دارد.');}if(p.passengers>=5&&(car.passengers||5)>=5){s+=5;reasons.push('برای ۵ سرنشین مناسب‌تر است.');}if(p.passengers<=2&&car.uses.includes('city'))s+=3;const value=getValueForMoney(car,p.budget);s+=Math.min(10,value.score/10);if(value.value==='بالا')reasons.push('نسبت قیمت به کیفیت و هزینه نگهداری جذاب‌تر است.');return{...car,match:Math.max(0,Math.min(99,s)),reasons:reasons.slice(0,4),valueScore:value.score,valueLabel:value.value,bestListing:getBestListing(car),listingCount:getListingsForCar(car.id).length};}
function formatDate(date){if(!date)return'نامشخص';const p=String(date).split('-'),m={'01':'فروردین','02':'اردیبهشت','03':'خرداد','04':'تیر','05':'مرداد','06':'شهریور','07':'مهر','08':'آبان','09':'آذر','10':'دی','11':'بهمن','12':'اسفند'};return p.length===3?`${p[2]} ${m[p[1]]||p[1]} ${p[0]}`:String(date);}
function formatPriceChange(c){if(!c)return'';if(c.direction==='flat')return'↔️ بدون تغییر نسبت به مشاهده قبلی';const sign=c.amount>0?'+':'';return`${c.amount>0?'📈':'📉'} تغییر اخیر: ${sign}${c.amount.toLocaleString('fa-IR')} میلیون (${sign}${c.percent.toFixed(1)}٪)`;}
if(form)form.addEventListener('submit',e=>{e.preventDefault();const p={budget:Number(document.getElementById('budget').value),gearbox:document.querySelector('input[name="gearbox"]:checked').value,use:document.querySelector('input[name="use"]:checked').value,priority:document.querySelector('input[name="priority"]:checked').value,year:document.querySelector('input[name="year"]:checked').value,passengers:Number(document.querySelector('input[name="passengers"]:checked').value)};const ranked=cars.map(c=>scoreCar(c,p)).sort((a,b)=>b.match-a.match).slice(0,3),old=document.getElementById('results');if(old)old.remove();const section=document.createElement('section');section.id='results';section.className='results';section.innerHTML=`<div class="results-head"><div><span class="eyebrow">تحلیل دستیار خودرو</span><h2>🚗 پیشنهادهای مناسب تو</h2></div><span class="experimental">قیمت‌ها تاریخ‌دارند؛ زنده نیستند</span></div>${ranked.map((c,i)=>{const l=c.bestListing;return`<article class="result-card ${i===0?'top-pick':''}"><div class="result-top"><div><span class="rank">پیشنهاد ${i+1}</span><h3>${c.name}</h3></div><div class="score"><strong>${Math.round(c.match)}٪</strong><small>تطابق</small></div></div><div class="price">حدود ${c.price.toLocaleString('fa-IR')} میلیون تومان</div><div class="price-meta">📅 آخرین مشاهده: ${formatDate(c.priceDate)} · منبع: ${c.priceSource||'داده پایه'}${c.priceIsMarket?' · بازار':' · پایه'}</div>${c.priceChange?`<div class="price-change ${c.priceChange.direction}">${formatPriceChange(c.priceChange)}</div>`:''}<div class="value-box"><strong>💰 ارزش خرید: ${c.valueLabel}</strong><span>امتیاز ارزش ${Math.round(c.valueScore)} از ۱۰۰</span></div>${l?`<div class="listing-box"><div><strong>🔎 بهترین آگهی نمونه</strong><span>${l.title} · ${l.city}</span></div><div class="listing-price">${Number(l.price).toLocaleString('fa-IR')} میلیون</div><div class="listing-gap ${l.verdict.tone}">${l.difference>0?'+':''}${Math.round(l.difference).toLocaleString('fa-IR')} میلیون نسبت به مرجع · ${l.verdict.label}</div><small>⚠️ نمونه آموزشی؛ برای تصمیم واقعی باید آگهی زنده و وضعیت خودرو بررسی شود.</small></div>`:''}<p class="reason-title">چرا اینو پیشنهاد دادیم؟</p><ul>${c.reasons.map(x=>`<li>${x}</li>`).join('')}</ul><div class="pros"><strong>نقاط قوت:</strong> ${c.pros.join('، ')}</div><div class="weakness"><strong>نقطه ضعف:</strong> ${c.cons.join('، ')}</div>${i===0?'<div class="best-badge">⭐ انتخاب پیشنهادی</div>':''}</article>`;}).join('')}<p class="data-note">آگهی‌های فعلی نمونه آموزشی‌اند و زنده نیستند. مرحله بعد، اتصال امن و سرورمحور به منابع واقعی و نرمال‌سازی آگهی‌هاست.</p>`;form.after(section);section.scrollIntoView({behavior:'smooth',block:'start'});});
