const cars = [
  {name:'پژو ۲۰۷ اتومات', price:700, score:9.2, gearbox:'auto', uses:['city','family'], priorities:['resale','fuel'], text:'گزینه‌ای متعادل برای استفاده شهری؛ بازار خرید و فروش مناسبی دارد.'},
  {name:'دنا پلاس دنده‌ای', price:650, score:8.8, gearbox:'manual', uses:['family','travel'], priorities:['cheap','comfort'], text:'فضای مناسب‌تر و انتخاب خوبی برای خانواده و سفر.'},
  {name:'سمند LX', price:520, score:8.1, gearbox:'manual', uses:['city','family','travel'], priorities:['cheap'], text:'قطعات فراوان و هزینه نگهداری نسبتاً قابل کنترل.'},
  {name:'تیبا ۲', price:430, score:7.9, gearbox:'manual', uses:['city'], priorities:['cheap','fuel'], text:'اقتصادی و مناسب استفاده روزمره شهری.'},
  {name:'کوییک اتومات', price:680, score:8.5, gearbox:'auto', uses:['city','family'], priorities:['fuel','resale'], text:'جمع‌وجور و مناسب شهر، با مزیت گیربکس اتومات.'}
];

const form=document.getElementById('car-form');
if(form){form.addEventListener('submit',e=>{e.preventDefault();const budget=Number(document.getElementById('budget').value);const gearbox=document.querySelector('input[name="gearbox"]:checked').value;const use=document.querySelector('input[name="use"]:checked').value;const priority=document.querySelector('input[name="priority"]:checked').value;let ranked=cars.map(car=>{let s=car.score;s+=Math.max(0,1-Math.abs(car.price-budget)/Math.max(budget,1))*2;if(gearbox==='any'||car.gearbox===gearbox)s+=2;if(car.uses.includes(use))s+=1.5;if(car.priorities.includes(priority))s+=1.5;return {...car,match:Math.min(9.9,s)};}).filter(car=>car.price<=budget*1.08).sort((a,b)=>b.match-a.match).slice(0,3);if(!ranked.length){ranked=cars.sort((a,b)=>Math.abs(a.price-budget)-Math.abs(b.price-budget)).slice(0,3);}let old=document.getElementById('results');if(old)old.remove();const section=document.createElement('section');section.id='results';section.className='how';section.innerHTML='<h2>🚗 پیشنهادهای دستیار خودرو</h2>'+ranked.map((car,i)=>`<div class="step" style="text-align:right;margin:12px 0"><b>پیشنهاد ${i+1}: ${car.name}</b><div>امتیاز تطابق: ${car.match.toFixed(1)} از ۱۰</div><div>قیمت مبنا: حدود ${car.price} میلیون تومان</div><span>${car.text}</span></div>`).join('');form.after(section);section.scrollIntoView({behavior:'smooth'});});}
