const cars = [
{name:'کوییک GX L',price:1220,gearbox:'manual',uses:['city','family'],priorities:['cheap','fuel'],year:'new',passengers:4,maintenance:8,economy:8,resale:8,comfort:6,reliability:7,pros:['هزینه نگهداری نسبتاً پایین','مناسب شهر'],weakness:'امکانات و کیفیت سواری متوسط.'},
{name:'پژو 207 TU3',price:1700,gearbox:'manual',uses:['city','family'],priorities:['resale','fuel'],year:'new',passengers:4,maintenance:7,economy:7,resale:9,comfort:7,reliability:7,pros:['بازار فروش قوی','قطعات و خدمات فراوان'],weakness:'فضای عقب محدودتر.'},
{name:'دنا پلاس اتوماتیک آپشنال',price:2900,gearbox:'auto',uses:['city','family','travel'],priorities:['comfort','resale'],year:'new',passengers:5,maintenance:6,economy:5,resale:8,comfort:8,reliability:6,pros:['فضای مناسب','مناسب خانواده و سفر'],weakness:'مصرف و هزینه نگهداری بالاتر.'},
{name:'تارا اتوماتیک V4',price:2850,gearbox:'auto',uses:['city','family','travel'],priorities:['comfort','resale'],year:'new',passengers:5,maintenance:6,economy:6,resale:8,comfort:8,reliability:7,pros:['فضای مناسب','تعادل خوب برای شهر و سفر'],weakness:'قیمت خرید بالاتر از گزینه‌های اقتصادی.'},
{name:'شاهین پلاس',price:2600,gearbox:'auto',uses:['city','family','travel'],priorities:['comfort','fuel'],year:'new',passengers:5,maintenance:6,economy:6,resale:7,comfort:8,reliability:6,pros:['فضای مناسب','گیربکس اتومات'],weakness:'بازار فروش ضعیف‌تر از 207.'},
{name:'ری‌را توربو',price:3800,gearbox:'auto',uses:['city','family','travel'],priorities:['comfort'],year:'new',passengers:5,maintenance:5,economy:5,resale:7,comfort:9,reliability:6,pros:['کراس‌اوور و امکانات بیشتر'],weakness:'هزینه خرید و نگهداری بالاتر.'}
];
const form=document.getElementById('car-form');
function scoreCar(car,p){let s=0;const reasons=[];const gap=Math.abs(car.price-p.budget)/Math.max(p.budget,1);s+=Math.max(0,30-gap*30);if(car.price<=p.budget){s+=15;reasons.push('داخل بودجه شماست.')}else{s-=8;reasons.push('کمی بالاتر از بودجه شماست.')}if(p.gearbox==='any'||car.gearbox===p.gearbox){s+=20;reasons.push(p.gearbox==='auto'?'گیربکس اتومات مطابق انتخاب شماست.':p.gearbox==='manual'?'گیربکس دنده‌ای مطابق انتخاب شماست.':'گیربکس با نیاز شما سازگار است.')}if(car.uses.includes(p.use)){s+=15;reasons.push(p.use==='city'?'برای استفاده شهری مناسب است.':p.use==='family'?'برای استفاده خانوادگی مناسب است.':'برای سفر مناسب است.')}if((p.priority==='cheap'&&car.maintenance>=7)||(p.priority==='fuel'&&car.economy>=7)||(p.priority==='resale'&&car.resale>=8)){s+=15;reasons.push(p.priority==='cheap'?'هزینه نگهداری امتیاز خوبی دارد.':p.priority==='fuel'?'مصرف اقتصادی‌تری دارد.':'بازار فروش بهتری دارد.')}if(p.passengers>=5&&car.passengers>=5){s+=5;reasons.push('برای ۵ سرنشین مناسب‌تر است.')}if(p.passengers<=2&&car.uses.includes('city'))s+=3;if(car.year===p.year)s+=5;return {...car,match:Math.max(0,Math.min(99,s)),reasons:reasons.slice(0,4)};}
if(form)form.addEventListener('submit',e=>{e.preventDefault();const p={budget:Number(document.getElementById('budget').value),gearbox:document.querySelector('input[name="gearbox"]:checked').value,use:document.querySelector('input[name="use"]:checked').value,priority:document.querySelector('input[name="priority"]:checked').value,year:document.querySelector('input[name="year"]:checked').value,passengers:Number(document.querySelector('input[name="passengers"]:checked').value)};let ranked=cars.map(c=>scoreCar(c,p)).sort((a,b)=>b.match-a.match).slice(0,3);const old=document.getElementById('results');if(old)old.remove();const section=document.createElement('section');section.id='results';section.className='results';section.innerHTML=`<div class="results-head"><div><span class="eyebrow">تحلیل دستیار خودرو</span><h2>🚗 پیشنهادهای مناسب تو</h2></div><span class="experimental">قیمت‌ها نمونه‌اند؛ قبل از خرید بررسی شوند</span></div>${ranked.map((c,i)=>`<article class="result-card ${i===0?'top-pick':''}"><div class="result-top"><div><span class="rank">پیشنهاد ${i+1}</span><h3>${c.name}</h3></div><div class="score"><strong>${Math.round(c.match)}٪</strong><small>تطابق</small></div></div><div class="price">حدود ${c.price.toLocaleString('fa-IR')} میلیون تومان</div><p class="reason-title">چرا اینو پیشنهاد دادیم؟</p><ul>${c.reasons.map(x=>`<li>${x}</li>`).join('')}</ul><div class="pros"><strong>نقاط قوت:</strong> ${c.pros.join('، ')}</div><div class="weakness"><strong>نقطه ضعف:</strong> ${c.weakness}</div>${i===0?'<div class="best-badge">⭐ انتخاب پیشنهادی</div>':''}</article>`).join('')}<p class="data-note">قیمت‌ها و امتیازها در این نسخه برای نمونه‌سازی هستند و برای خرید واقعی باید با داده روز بازار و کارشناسی خودرو به‌روزرسانی شوند.</p>`;form.after(section);section.scrollIntoView({behavior:'smooth',block:'start'});});
